name: Doc-test

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  doc-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - run: docker pull exercism/factor-test-runner
      - name: Verify introduction.md examples
        run: python3 bin/test-doc-examples
